[31mCMake Error at ament_cmake_symlink_install/ament_cmake_symlink_install.cmake:5 (file):
  file failed to open for writing (Permission denied):

    /home/nick/Robotics_Projects/furuta1/build/ros_gz_example_application/symlink_install_manifest.txt
Call Stack (most recent call first):
  cmake_install.cmake:46 (include)

[0m
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/nick/Robotics_Projects/furuta1/install/ros_gz_example_application/share/colcon-core/packages'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__
    rc = await self.task(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__
    return await task_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_cmake/build.py", line 84, in build
    create_environment_scripts(
  File "/usr/lib/python3/dist-packages/colcon_core/environment/__init__.py", line 89, in create_environment_scripts
    create_file_with_runtime_dependencies(prefix_path, pkg))
  File "/usr/lib/python3/dist-packages/colcon_core/environment/__init__.py", line 171, in create_file_with_runtime_dependencies
    path.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/home/nick/Robotics_Projects/furuta1/install/ros_gz_example_application/share/colcon-core'
